import React, { useState, useEffect, useMemo } from "react";
import axios from "axios";
import {
  BrowserRouter as Router,
  Routes,
  Route,
  Navigate,
} from "react-router-dom";

import "./App.css";

// Components
import Sidebar from "./components/Sidebar";
import Dashboard from "./components/Dashboard";
import Operation from "./components/Operation";
import Analytics from "./components/Analytics";
import Team from "./components/Team";
import Profile from "./components/Profile";

function App() {
  const [tasks, setTasks] = useState([]);
  const [recentTasks, setRecentTasks] = useState([]);

    
   const initialTasks = [
  {
    sno: 1,
    date: "01-07-2026",
    name: "Srishti",
    task: "Re: Intellectt Inc ( AI & Generative AI Training )- SSDN Technologies",
    timing: "10:33 AM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 2,
    date: "01-07-2026",
    name: "Amit",
    task: "Re: Exploring Collaboration Opportunities with Kaplan ME + MOM",
    timing: "11:17 AM",
    remarks: "Closed",
    completedTime: "4:30 PM",
    completedDate: "01-07-2026",
  },
  {
    sno: 3,
    date: "01-07-2026",
    name: "Srishti",
    task: "Re: Proposal : Questionnaire_RE: SSDN Technologies_Beyond Codes Discussion",
    timing: "11:56 AM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 4,
    date: "01-07-2026",
    name: "Srishti",
    task: "Re: [ENQUIRY] Hawksford ( Microsoft Copilot Training ) || SSDN Technologies",
    timing: "12:02 PM",
    remarks: "In-Process",
    completedTime: "Reply (8:51 AM)",
    completedDate: "",
  },
  {
    sno: 5,
    date: "01-07-2026",
    name: "Amit",
    task: "Re: Exploring Collaboration Opportunity | SSDN Technologies & LeadSpire Consulting",
    timing: "12:46 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 6,
    date: "01-07-2026",
    name: "Shivam",
    task: "RE: Issue with LAB",
    timing: "12:57 PM",
    remarks: "Respond Share",
    completedTime: "1:15 PM",
    completedDate: "01-07-2026",
  },
  {
    sno: 7,
    date: "01-07-2026",
    name: "Srishti",
    task: "Zaptas Technologies Pvt Ltd. ( Microsoft ) || SSDN Technologies",
    timing: "1:07 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 8,
    date: "01-07-2026",
    name: "Srishti",
    task: "Re: [External] Re: Buckman Laboratories ( Lean six sigma black belt ) – SSDN Technologies",
    timing: "1:23 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 9,
    date: "01-07-2026",
    name: "Shivam",
    task: "Re: [External] Re: Buckman Laboratories ( Lean six sigma black belt ) – SSDN Technologies",
    timing: "1:33 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 10,
    date: "01-07-2026",
    name: "Kamal",
    task: "Re: Training+Lab and Extended Lab Requirement | Citrix VDI AVD L2 - AMJ'26",
    timing: "2:17 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "3:38 PM",
    completedDate: "01-07-2026",
  },
  {
    sno: 11,
    date: "01-07-2026",
    name: "Shivam",
    task: "Facing in Lab Environment – Impact on Training Activities By Gorantla",
    timing: "2:47 PM",
    remarks: "Respond Share",
    completedTime: "4:21 PM",
    completedDate: "01-07-2026",
  },
  {
    sno: 12,
    date: "01-07-2026",
    name: "Shivam",
    task: "Facing in Lab Environment – Impact on Training Activities By",
    timing: "3:02 PM",
    remarks: "Respond Share",
    completedTime: "4:24 PM",
    completedDate: "01-07-2026",
  },
  {
    sno: 13,
    date: "01-07-2026",
    name: "Kamal",
    task: "Re: IBM BAW Training",
    timing: "3:20 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 14,
    date: "01-07-2026",
    name: "Amit",
    task: "Business Collaboration Call with Kaplan ME || SSDN Technologies (Amit, Mukesh, Srishti, Shivam)",
    timing: "3:00 PM",
    remarks: "CALL",
    completedTime: "3:25 PM",
    completedDate: "01-07-2026",
  },
  {
    sno: 15,
    date: "01-07-2026",
    name: "Shivam",
    task: "Re: Request for Extended Labs | SCCM + Intune L2 (Batch 1) 19 June-20 July'26",
    timing: "3:26 PM",
    remarks: "Solution",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 16,
    date: "01-07-2026",
    name: "Srishti",
    task: "Landmark Group ( Cloudflare Training ) || SSDN Technologies",
    timing: "3:56 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 17,
    date: "01-07-2026",
    name: "Kanika",
    task: "Re: AI & Generative AI- Training Requirement",
    timing: "4:27 PM",
    remarks: "Closed",
    completedTime: "6:30 PM",
    completedDate: "01-07-2026",
  },
  {
    sno: 18,
    date: "01-07-2026",
    name: "Srishti",
    task: "Kion Group ( OT Security Course (SCADA, PLCs) Training ) || SSDN Technologies",
    timing: "4:46 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 19,
    date: "01-07-2026",
    name: "Amit",
    task: "Re: Exploring Collaboration Opportunities with Kaplan ME",
    timing: "5:10 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 20,
    date: "01-07-2026",
    name: "Srishti",
    task: "Re: Generative AI Trainer Requirement – Finance & Procurement | SSDN Technologies",
    timing: "5:10 PM",
    remarks: "Closed",
    completedTime: "5:10 PM",
    completedDate: "01-07-2026",
  },
  {
    sno: 21,
    date: "01-07-2026",
    name: "Srishti",
    task: "Re: Raja Spiritual Private Limited (Retail Sales team training) - SSDN Technologies",
    timing: "5:19 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 22,
    date: "01-07-2026",
    name: "Srishti",
    task: "RE: Urgent Request for Training Course Information",
    timing: "6:20 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 23,
    date: "01-07-2026",
    name: "Srishti",
    task: "Re: Saheel Properties (Pre-Sales Training) || SSDN Technologies",
    timing: "6:33 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 24,
    date: "01-07-2026",
    name: "Srishti",
    task: "Re: Urgent Request for Training Course Information",
    timing: "6:42 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 25,
    date: "01-07-2026",
    name: "Srishti",
    task: "RE: Kion Group ( OT Security Course (SCADA, PLCs) Training ) || SSDN Technologies",
    timing: "6:45 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
    {
    sno: 26,
    date: "01-07-2026",
    name: "Shivam",
    task: "Re: IBM BAW Training Requirement ||",
    timing: "7:11 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 27,
    date: "02-07-2026",
    name: "Shivam",
    task: "RE: Training request - Citrix DAAS",
    timing: "7:46 AM",
    remarks: "Closed",
    completedTime: "2:51 PM",
    completedDate: "02-07-2026",
  },
  {
    sno: 28,
    date: "02-07-2026",
    name: "Kamal",
    task: "RE: Training+Lab and Extended Lab Requirement | Citrix VDI AVD L2 - AMJ'26",
    timing: "7:49 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 29,
    date: "02-07-2026",
    name: "Kamal",
    task: "RE: MDM Training",
    timing: "08:05",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 30,
    date: "02-07-2026",
    name: "Srishti",
    task: "PRIMUS Techsystems Private Limited (SAP PS Corporate Trainer) || SSDN Technologies",
    timing: "11:41 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 31,
    date: "02-07-2026",
    name: "Kamal",
    task: "IBM BAW Training",
    timing: "2:23 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 32,
    date: "02-07-2026",
    name: "Shivam",
    task: "Managed Services + Content + Labs requirement for Cisco ENAUTO training - Enterprise Customer (Jul'26)",
    timing: "2:28 PM",
    remarks: "Closed",
    completedTime: "2:50 PM",
    completedDate: "02-07-2026",
  },
  {
    sno: 33,
    date: "02-07-2026",
    name: "Amit",
    task: "Network Cabling Design Training Requirement Support | SSDN Technologies",
    timing: "2:47 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 34,
    date: "02-07-2026",
    name: "Shivam",
    task: "Re: Lean Six Sigma Black Belt - Offline Training Requirement",
    timing: "2:52 PM",
    remarks: "Closed",
    completedTime: "4:33 PM",
    completedDate: "02-07-2026",
  },
  {
    sno: 35,
    date: "02-07-2026",
    name: "Srishti",
    task: "Future Architectural Glass LLC (Future Glass) (Leadership & Supervisory Development Program Training) || SSDN Technologies",
    timing: "3:29 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 36,
    date: "02-07-2026",
    name: "Kamal",
    task: "Extended Lab Initiation - SCCM + Intune L2-Module 2 _OND'25",
    timing: "4:09 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 37,
    date: "02-07-2026",
    name: "Srishti",
    task: "Re: Kion Group (OT Security Course (SCADA, PLCs) Training) || SSDN Technologies",
    timing: "4:10 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 38,
    date: "02-07-2026",
    name: "Kamal",
    task: "Managerial Effectiveness Program || Maharishi Ayurveda x SSDN Technologies ||",
    timing: "4:42 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 39,
    date: "02-07-2026",
    name: "Amit",
    task: "RE: Exploring Collaboration Opportunities with Kaplan ME",
    timing: "4:45 PM",
    remarks: "Closed",
    completedTime: "5:30 PM",
    completedDate: "02-07-2026",
  },
  {
    sno: 40,
    date: "02-07-2026",
    name: "Srishti",
    task: "Re: Viva Composite Panel (Posh Training) || SSDN Technologies",
    timing: "5:04 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 41,
    date: "02-07-2026",
    name: "Srishti",
    task: "Re: Landmark Group (Cloudflare Training) || SSDN Technologies",
    timing: "5:19 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 42,
    date: "02-07-2026",
    name: "Shivam",
    task: "RE: Managed Services + Content + Labs requirement for Cisco ENAUTO training - Enterprise Customer (Jul'26)",
    timing: "5:23 PM",
    remarks: "Closed",
    completedTime: "6:07 PM",
    completedDate: "02-07-2026",
  },
  {
    sno: 43,
    date: "02-07-2026",
    name: "Srishti",
    task: "Re: Intellectt Inc (AI & Generative AI Training) - SSDN Technologies",
    timing: "5:47 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 44,
    date: "02-07-2026",
    name: "Kamal",
    task: "Re: Corporate Grooming & Corporate Readiness Training Program || GD Goenka x SSDN Technologies ||",
    timing: "6:14 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 45,
    date: "02-07-2026",
    name: "Kamal",
    task: "Training request - Citrix DAAS",
    timing: "6:30 PM",
    remarks: "CALL",
    completedTime: "6:50 PM",
    completedDate: "02-07-2026",
  },
  {
    sno: 46,
    date: "02-07-2026",
    name: "Kamal",
    task: "RE: Extended Lab Initiation - SCCM + Intune L2-Module 2 _OND'25",
    timing: "6:31 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 47,
    date: "02-07-2026",
    name: "Shivam",
    task: "Re: Cyber Security Awareness Month Program",
    timing: "6:59 PM",
    remarks: "Closed",
    completedTime: "10:58 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 48,
    date: "02-07-2026",
    name: "Kamal",
    task: "RE: Training request - Citrix DAAS",
    timing: "7:32 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 49,
    date: "03-07-2026",
    name: "Srishti",
    task: "BluSwap (Soft Skills Training) || SSDN Technologies",
    timing: "10:39 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 50,
    date: "03-07-2026",
    name: "Amit",
    task: "Re: AI Trainer Support & Collaboration Opportunity",
    timing: "11:00 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
    {
    sno: 51,
    date: "03-07-2026",
    name: "Shivam",
    task: "RE: Training+Lab and Extended Lab Requirement | Intune L2 - AMJ'26",
    timing: "12:01 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 52,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Tender",
    timing: "12:14 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 53,
    date: "03-07-2026",
    name: "Srishti",
    task: "Business Collaboration Opportunity with SSDN Technologies",
    timing: "12:16 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 54,
    date: "03-07-2026",
    name: "Amit",
    task: "Leadership Development Training Discussion | 3 July 2026 | 11:00 AM (Dubai Time) | SSDN Technologies",
    timing: "12:30 PM",
    remarks: "CALL",
    completedTime: "12:45 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 55,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Meeting Request to Discuss Our Ongoing Partnership - SSDN Technologies",
    timing: "12:49 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 56,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Jerico Technologies (Networking Training) – SSDN Technologies",
    timing: "1:20 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 57,
    date: "03-07-2026",
    name: "Amit",
    task: "Re: Exploring a Learning & Development Collaboration Opportunity with Marriott Hotels",
    timing: "1:28 PM",
    remarks: "Closed",
    completedTime: "1:26 PM",
    completedDate: "07-07-2026",
  },
  {
    sno: 58,
    date: "03-07-2026",
    name: "Shivam",
    task: "Re: Exploring a Learning & Development Collaboration Opportunity with Marriott Hotels",
    timing: "1:33 PM",
    remarks: "Closed",
    completedTime: "1:26 PM",
    completedDate: "07-07-2026",
  },
  {
    sno: 59,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: [External] Re: Buckman Laboratories (Lean Six Sigma Black Belt) – SSDN Technologies",
    timing: "1:43 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 60,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Proposal: Questionnaire_RE: SSDN Technologies_Beyond Codes Discussion",
    timing: "1:45 PM",
    remarks: "Closed",
    completedTime: "1:45 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 61,
    date: "03-07-2026",
    name: "Srishti",
    task: "Discussion Meeting with Hawksford || SSDN Technologies",
    timing: "2:00 PM",
    remarks: "CALL",
    completedTime: "2:30 PM",
    completedDate: "",
  },
  {
    sno: 62,
    date: "03-07-2026",
    name: "Kamal",
    task: "Introducing Excellence Through Empowerment Program || UCB x SSDN Technologies ||",
    timing: "2:20 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 63,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Jerico Technologies (Networking Training) – SSDN Technologies",
    timing: "2:51 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 64,
    date: "03-07-2026",
    name: "Mukesh",
    task: "Re: Partner Opportunity: Reduced Certification Costs & Enhanced Training Programs",
    timing: "3:16 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 65,
    date: "03-07-2026",
    name: "Shivam",
    task: "Re: Urgent Requirement – Zafran Training (VILT)",
    timing: "3:20 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 66,
    date: "03-07-2026",
    name: "Shivam",
    task: "Re: Confirmation on SCCM Training || Offline - Sri Lanka",
    timing: "3:49 PM",
    remarks: "Closed",
    completedTime: "6:31 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 67,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: [ENQUIRY] Hawksford (Microsoft Copilot Training) || SSDN Technologies",
    timing: "3:49 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 68,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Landmark Group (Cloudflare Training) || SSDN Technologies",
    timing: "3:58 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 69,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Training Request - Citrix DAAS",
    timing: "4:03 PM",
    remarks: "Closed",
    completedTime: "6:16 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 70,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Jerico Technologies (Networking Training) – SSDN Technologies",
    timing: "4:05 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
    {
    sno: 71,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Posh Training x SSDN Technologies || Offline || Noida ||",
    timing: "4:05 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 72,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Training request - Citrix DAAS",
    timing: "4:05 PM",
    remarks: "Closed",
    completedTime: "5:52 PM",
    completedDate: "06-07-2026",
  },
  {
    sno: 73,
    date: "03-07-2026",
    name: "Kamal",
    task: "Introducing Excellence Through Empowerment Program || SSDN Technologies ||",
    timing: "4:12 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 74,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Kion Group (OT Security Course (SCADA, PLCs) Training) || SSDN Technologies",
    timing: "4:49 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 75,
    date: "03-07-2026",
    name: "Shivam",
    task: "Re: ITIL Version 5 Foundation",
    timing: "5:28 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 76,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: VT Requirement_Lucknow & Madurai || Professional",
    timing: "5:35 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 77,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Quote for CSAM'26",
    timing: "5:35 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 78,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: PR725073 - PANW XSIAM Certifications Vouchers",
    timing: "5:38 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 79,
    date: "03-07-2026",
    name: "Kamal",
    task: "5+D80",
    timing: "5:39 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 80,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Request for Training Session – TechBee HR Team",
    timing: "5:42 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 81,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Trainer Profile Required | OCI IAM Cloud Training - Instructor Led | BRP | OEM",
    timing: "5:43 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 82,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Hydraulics & CATIA V5 Training",
    timing: "5:44 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 83,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Soft Skills Training Program || AAR One x SSDN Technologies ||",
    timing: "5:47 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 84,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Proposal for Enterprise AI Workforce Transformation for HCLTech",
    timing: "5:48 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 85,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Omnissa Workspace One from our client Cognizant",
    timing: "5:50 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 86,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Request for AWS Programs and Pricing (GPS)",
    timing: "5:51 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 87,
    date: "03-07-2026",
    name: "Srishti",
    task: "Business Collaboration Opportunity with SSDN Technologies",
    timing: "5:52 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 88,
    date: "03-07-2026",
    name: "Shivam",
    task: "RE: Vendor / Staffing Needs - AI Awareness",
    timing: "5:54 PM",
    remarks: "Closed",
    completedTime: "5:54 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 89,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: License Requirement for Enterprise Customer Training Program - ISTQB CT-GenAI (Jul'26)",
    timing: "5:56 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 90,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Managed Services + Content + Labs Requirement for Cisco NIOS DDI Operations, Administration & Deployment Training - Enterprise Customer (Jul'26)",
    timing: "5:57 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 91,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Raja Spiritual Private Limited (Retail Sales Team Training) - SSDN Technologies",
    timing: "6:29 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 92,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Corporate Grooming & Corporate Readiness Training Program || GD Goenka x SSDN Technologies ||",
    timing: "6:33 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 93,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Meeting Request to Discuss Our Ongoing Partnership - SSDN Technologies",
    timing: "6:36 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 94,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Lab Requirement || SRE Automation Lab / Observability Lab / Cloud Lab",
    timing: "6:40 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 95,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Managed Services + Content + Labs Requirement for Cisco SD-WAN, SDWSEC Training - Enterprise Customer (Jul'26)",
    timing: "6:41 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
    {
    sno: 96,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Managed Services + Content + Labs Requirement for Cisco SCAZT Training - Enterprise Customer (Jul'26)",
    timing: "6:42 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 97,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Training Requirement : BRP_Azure Stack HCI 2603_Training",
    timing: "6:43 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 98,
    date: "03-07-2026",
    name: "Kamal",
    task: "Re: Soft Skills Training Program || BluSwap x SSDN Technologies ||",
    timing: "6:46 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 99,
    date: "03-07-2026",
    name: "Shivam",
    task: "RE: Resolution Screen Issue",
    timing: "6:46 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "6:58 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 100,
    date: "03-07-2026",
    name: "Srishti",
    task: "Re: Saheel Properties (Pre-Sales Training) || SSDN Technologies",
    timing: "6:56 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 101,
    date: "03-07-2026",
    name: "Shivam",
    task: "RE: Facing in Lab Environment – Impact on Training Activities",
    timing: "6:58 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 102,
    date: "03-07-2026",
    name: "Shivam",
    task: "Re: Resolution Screen Issue",
    timing: "7:01 PM",
    remarks: "Closed",
    completedTime: "7:12 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 103,
    date: "03-07-2026",
    name: "Shivam",
    task: "RE: Facing in Lab Environment – Impact on Training Activities",
    timing: "7:19 PM",
    remarks: "Closed",
    completedTime: "8:09 PM",
    completedDate: "03-07-2026",
  },
  {
    sno: 104,
    date: "03-07-2026",
    name: "Shivam",
    task: "RE: Vendor / Staffing Needs - AI Awareness",
    timing: "7:25 PM",
    remarks: "Closed",
    completedTime: "10:45 PM",
    completedDate: "06-07-2026",
  },
  {
    sno: 105,
    date: "04-07-2026",
    name: "Kamal",
    task: "Re: Lab Discussion Call",
    timing: "3:00 PM",
    remarks: "CALL",
    completedTime: "3:50 PM",
    completedDate: "04-07-2026",
  },
  {
    sno: 106,
    date: "06-07-2026",
    name: "Amit",
    task: "Re: CMDB Training Program Support | SSDN Technologies",
    timing: "9:41 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 107,
    date: "06-07-2026",
    name: "Amit",
    task: "Exploring Corporate Training Support for WattMonk Technologies",
    timing: "10:29 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 108,
    date: "06-07-2026",
    name: "Srishti",
    task: "Exploring Strategic Collaboration Opportunities with Ericsson || SSDN Technologies",
    timing: "10:50 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 109,
    date: "06-07-2026",
    name: "Shivam",
    task: "RE: Managed Services + Content + Labs Requirement for Cisco ENAUTO Training - Enterprise Customer (Jul'26)",
    timing: "11:10 AM",
    remarks: "Closed",
    completedTime: "5:11 PM",
    completedDate: "",
  },
  {
    sno: 110,
    date: "06-07-2026",
    name: "Srishti",
    task: "Exploring Strategic Collaboration Opportunities with Mohindra Fasteners Limited || SSDN Technologies",
    timing: "11:23 AM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 111,
    date: "06-07-2026",
    name: "Amit",
    task: "Re: Exploring an Overseas Partnership Between Meirc & SSDN Technologies",
    timing: "11:37 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 112,
    date: "06-07-2026",
    name: "Kamal",
    task: "Re: Corporate Grooming & Corporate Readiness Training Program || GD Goenka x SSDN Technologies ||",
    timing: "11:53 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 113,
    date: "06-07-2026",
    name: "Kamal",
    task: "Re: Soft Skills Training Program || BluSwap x SSDN Technologies ||",
    timing: "12:23 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 114,
    date: "06-07-2026",
    name: "Srishti",
    task: "Re: Kion Group (OT Security Course (SCADA, PLCs) Training) || SSDN Technologies",
    timing: "12:27 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 115,
    date: "06-07-2026",
    name: "Amit",
    task: "Partner Opportunity: Reduced Certification Costs & Enhanced Training Programs",
    timing: "12:38 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 116,
    date: "06-07-2026",
    name: "Srishti",
    task: "Exploring Strategic Collaboration Opportunities with ISIM (AI Training) || SSDN Technologies",
    timing: "12:47 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 117,
    date: "06-07-2026",
    name: "Amit",
    task: "Partner Opportunity: Reduced Certification Costs & Enhanced Training Programs",
    timing: "12:55 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 118,
    date: "06-07-2026",
    name: "Amit",
    task: "Re: Partner Opportunity: Reduced Certification Costs & Enhanced Training Programs (moshahid@learnerspoint.org)",
    timing: "1:18 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 119,
    date: "06-07-2026",
    name: "Shivam",
    task: "RE: Managed Services + Content + Labs Requirement for Cisco Agentic Workflows Training - Enterprise Customer (Jul'26)",
    timing: "1:18 PM",
    remarks: "Closed",
    completedTime: "2:03 PM",
    completedDate: "",
  },
  {
    sno: 120,
    date: "06-07-2026",
    name: "Amit",
    task: "Re: ITIL 5 Foundation Training Support | SSDN Technologies",
    timing: "1:41 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
    {
    sno: 121,
    date: "06-07-2026",
    name: "Amit",
    task: "Partner Opportunity: Reduced Certification Costs & Enhanced Training Programs",
    timing: "1:57 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 122,
    date: "06-07-2026",
    name: "Amit",
    task: "Re: Exploring a Collaboration Opportunity Between Meirc & SSDN Technologies",
    timing: "2:51 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 123,
    date: "06-07-2026",
    name: "Mukesh",
    task: "Business Collaboration THINKSMART || SSDN Technologies",
    timing: "3:00 PM",
    remarks: "CALL",
    completedTime: "3:30 PM",
    completedDate: "",
  },
  {
    sno: 124,
    date: "06-07-2026",
    name: "Srishti",
    task: "Re: AI & Prompt Engineering || SSDN Technologies",
    timing: "3:15 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 125,
    date: "06-07-2026",
    name: "Kamal",
    task: "BluSwap x SSDN Technologies || 6 July 2026 || 3:30 PM IST ||",
    timing: "3:30 PM",
    remarks: "CALL",
    completedTime: "4:00 PM",
    completedDate: "",
  },
  {
    sno: 126,
    date: "06-07-2026",
    name: "Amit",
    task: "Regarding Your Citrix CTX-202 Training Requirement Support | SSDN Technologies",
    timing: "5:08 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 127,
    date: "06-07-2026",
    name: "Srishti",
    task: "Re: [External] Re: Buckman Laboratories (Lean Six Sigma Black Belt) – SSDN Technologies",
    timing: "5:22 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 128,
    date: "06-07-2026",
    name: "Srishti",
    task: "Re: Landmark Group (Cloudflare Training) || SSDN Technologies",
    timing: "5:39 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 129,
    date: "06-07-2026",
    name: "Kamal",
    task: "Re: BRP Request | SQL_Profi_Bruns",
    timing: "5:44 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 130,
    date: "06-07-2026",
    name: "Srishti",
    task: "Re: Future Architectural Glass LLC (Future Glass) (Leadership & Supervisory Development Program Training) || SSDN Technologies",
    timing: "6:18 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 131,
    date: "06-07-2026",
    name: "Srishti",
    task: "Re: Raja Spiritual Private Limited (Retail Sales Team Training) - SSDN Technologies",
    timing: "6:25 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 132,
    date: "06-07-2026",
    name: "Srishti",
    task: "Re: Intellectt Inc (AI & Generative AI Training) - SSDN Technologies",
    timing: "6:47 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 133,
    date: "06-07-2026",
    name: "Kamal",
    task: "Re: Enquiry for the ISO 42001 Lead Auditor Certification",
    timing: "7:36 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 134,
    date: "07-07-2026",
    name: "Amit",
    task: "Re: CMDB Training Program Support | SSDN Technologies",
    timing: "9:10 AM",
    remarks: "Closed",
    completedTime: "9:10 AM",
    completedDate: "",
  },
  {
    sno: 135,
    date: "07-07-2026",
    name: "Amit",
    task: "Re: Exploring a Learning & Development Collaboration Opportunity with Marriott Hotels",
    timing: "9:10 AM",
    remarks: "Closed",
    completedTime: "1:26 PM",
    completedDate: "07-07-2026",
  },
  {
    sno: 136,
    date: "07-07-2026",
    name: "Amit",
    task: "Re: Regarding Your Citrix CTX-202 Training Requirement Support | SSDN Technologies",
    timing: "9:30 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 137,
    date: "07-07-2026",
    name: "Amit",
    task: "Re: Partner Opportunity: Reduced Certification Costs & Enhanced Training Programs",
    timing: "10:30 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 138,
    date: "07-07-2026",
    name: "Kamal",
    task: "ISO 42001 Lead Auditor Training & Certification || Public Batch Cost || India Region ||",
    timing: "10:48 AM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 139,
    date: "07-07-2026",
    name: "Kamal",
    task: "Nepra Resource Management Pvt. Ltd x SSDN Technologies || Training Partner Empanelment ||",
    timing: "11:12 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 140,
    date: "07-07-2026",
    name: "Srishti",
    task: "Exploring Strategic Collaboration Opportunities with The Leela Palaces || SSDN Technologies",
    timing: "11:20 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
    {
    sno: 141,
    date: "07-07-2026",
    name: "Kamal",
    task: "Re: POSH Training || AnjuSmriti x SSDN Technologies ||",
    timing: "11:21 AM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 142,
    date: "07-07-2026",
    name: "Kamal",
    task: "Re: Soft Skills Training Program || AAR One x SSDN Technologies ||",
    timing: "11:33 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 143,
    date: "07-07-2026",
    name: "Kamal",
    task: "Re: Corporate Grooming & Corporate Readiness Training Program || GD Goenka x SSDN Technologies ||",
    timing: "11:36 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 144,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: Viva Composite Panel (Posh Training) || SSDN Technologies",
    timing: "12:24 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 145,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: Vridhi Home Finance (Soft Skills - Leadership Development Training for Senior Managers Level 3) || SSDN Technologies",
    timing: "12:28 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 146,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: Exploring Strategic Collaboration Opportunities with Mohindra Fasteners Limited || SSDN Technologies",
    timing: "12:41 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 147,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: KGOC Global (Sales Training) || SSDN Technologies",
    timing: "12:45 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 148,
    date: "07-07-2026",
    name: "Kamal",
    task: "Reg: Excel Program & Introducing Excellence Through Empowerment Program || Brick 2 Wall x SSDN Technologies ||",
    timing: "12:59 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 149,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: Kion Group (OT Cyber Security Training) || SSDN Technologies",
    timing: "1:07 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 150,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: [ENQUIRY] Hawksford (Microsoft Copilot Training) || SSDN Technologies",
    timing: "1:17 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 151,
    date: "07-07-2026",
    name: "Kamal",
    task: "Re: Introducing Excellence Through Empowerment Program || SSDN Technologies ||",
    timing: "1:32 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 152,
    date: "07-07-2026",
    name: "Amit",
    task: "Re: Training, Certification & Lab Support Partnership Opportunity",
    timing: "1:36 PM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 153,
    date: "07-07-2026",
    name: "Amit",
    task: "Re: Python Training Requirement Support | SSDN Technologies",
    timing: "1:40 PM",
    remarks: "Closed",
    completedTime: "1:49 PM",
    completedDate: "07-07-2026",
  },
  {
    sno: 154,
    date: "07-07-2026",
    name: "Kamal",
    task: "Introducing Excellence Through Empowerment Program ||",
    timing: "1:40 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 155,
    date: "07-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "1:47 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 156,
    date: "07-07-2026",
    name: "Kamal",
    task: "Excellence Through Empowerment Program || Future Focus Infotech x SSDN Technologies ||",
    timing: "1:52 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 157,
    date: "07-07-2026",
    name: "Mukesh",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution || SSDN Technologies",
    timing: "1:53 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 158,
    date: "07-07-2026",
    name: "Kamal",
    task: "Re: Azure Subscription for Azure AI AI-900 Course || For Python with Agentic AI Training",
    timing: "1:54 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 159,
    date: "07-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "3:03 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 160,
    date: "07-07-2026",
    name: "Amit",
    task: "Generative AI Training Requirement Support | SSDN Technologies",
    timing: "3:07 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 161,
    date: "07-07-2026",
    name: "Amit",
    task: "Data Analytics Training Requirement Support | SSDN Technologies",
    timing: "3:17 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 162,
    date: "07-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "3:28 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 163,
    date: "07-07-2026",
    name: "Kamal",
    task: "Soft Skills Program Requirement in Jaipur || JCB x SSDN Technologies ||",
    timing: "4:01 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 164,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: Landmark Group (Cloudflare Training) || SSDN Technologies",
    timing: "4:14 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 165,
    date: "07-07-2026",
    name: "Kamal",
    task: "Introducing Excellence Through Empowerment Program || Wipro x SSDN Technologies ||",
    timing: "4:29 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
    {
    sno: 166,
    date: "07-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "4:34 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 167,
    date: "07-07-2026",
    name: "Kamal",
    task: "Introducing Excellence Through Empowerment Program || A Year-Aligned Program ||",
    timing: "4:42 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 168,
    date: "07-07-2026",
    name: "Kamal",
    task: "Request for Meeting to Resume Training Engagement as Empaneled Partner ||",
    timing: "4:56 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 169,
    date: "07-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "4:58 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 170,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: Saheel Properties (Pre-Sales Training) || SSDN Technologies",
    timing: "6:48 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 171,
    date: "07-07-2026",
    name: "Srishti",
    task: "Re: Meeting Request to Discuss Our Ongoing Partnership - SSDN Technologies",
    timing: "6:51 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 172,
    date: "08-07-2026",
    name: "Amit",
    task: "Re: Training, Certification & Lab Support Partnership Opportunity",
    timing: "10:00 AM",
    remarks: "In-Process",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 173,
    date: "08-07-2026",
    name: "Shivam",
    task: "Re: Training Requirement – Fortinet SASE Training",
    timing: "10:18 AM",
    remarks: "Closed",
    completedTime: "11:51 AM",
    completedDate: "08-07-2026",
  },
  {
    sno: 174,
    date: "08-07-2026",
    name: "Srishti",
    task: "Soft Skills Training for Vedalex World Class Products Pvt. Ltd. || SSDN Technologies",
    timing: "10:45 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 175,
    date: "08-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "11:16 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 176,
    date: "08-07-2026",
    name: "Amit",
    task: "Citrix CVAD 301 Training Proposal | SSDN Technologies",
    timing: "11:27 AM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 177,
    date: "08-07-2026",
    name: "Amit",
    task: "Re: Exploring a Learning & Development Collaboration Opportunity with Marriott Hotels",
    timing: "11:45 AM",
    remarks: "Closed",
    completedTime: "12:06 PM",
    completedDate: "08-07-2026",
  },
  {
    sno: 178,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: [ENQUIRY] Hawksford (Microsoft Copilot Training) || SSDN Technologies",
    timing: "12:02 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 179,
    date: "08-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution (ratika.dayal@in.ey.com)",
    timing: "12:07 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 180,
    date: "08-07-2026",
    name: "Kamal",
    task: "Excellence Through Empowerment || A Year-Round Learning Solution ||",
    timing: "12:08 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 181,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: [External] Re: Buckman Laboratories (Lean Six Sigma Black Belt) – SSDN Technologies",
    timing: "12:18 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 182,
    date: "08-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution (sukumarip@kpmg.com)",
    timing: "12:21 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 183,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: Intellectt Inc (AI & Generative AI Training) - SSDN Technologies",
    timing: "12:33 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 184,
    date: "08-07-2026",
    name: "Kamal",
    task: "Re: Extended Lab Initiation - SCCM + Intune L2-Module 2 _OND'25",
    timing: "12:40 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 185,
    date: "08-07-2026",
    name: "Kamal",
    task: "Re: BRP_Aruba Wireless",
    timing: "12:58 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 186,
    date: "08-07-2026",
    name: "Srishti",
    task: "OT Cyber Security Training for Kion Group || SSDN Technologies",
    timing: "1:18 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 187,
    date: "08-07-2026",
    name: "Kamal",
    task: "Re: BRP_Cisco Board Pro",
    timing: "1:24 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 188,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: OT Cyber Security Training for Kion Group || SSDN Technologies",
    timing: "1:32 PM",
    remarks: "Closed",
    completedTime: "6:55 PM",
    completedDate: "08-07-2026",
  },
  {
    sno: 189,
    date: "08-07-2026",
    name: "Kamal",
    task: "Re: Soft Skills Training Program || AAR One x SSDN Technologies ||",
    timing: "1:36 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 190,
    date: "08-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution (dipak.s@bgccl.com)",
    timing: "1:43 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
    {
    sno: 191,
    date: "08-07-2026",
    name: "Kamal",
    task: "Re: Soft Skills Program Requirement in Jaipur || JCB x SSDN Technologies ||",
    timing: "2:19 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 192,
    date: "08-07-2026",
    name: "Amit",
    task: "Citrix CVAD 301 Training Proposal | SSDN Technologies",
    timing: "2:20 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 193,
    date: "08-07-2026",
    name: "Amit",
    task: "Re: Python Training Requirement Support | SSDN Technologies",
    timing: "2:23 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 194,
    date: "08-07-2026",
    name: "Kamal",
    task: "Re: Request for Meeting to Resume Training Engagement as Empaneled Partner ||",
    timing: "2:30 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 195,
    date: "08-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "2:49 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 196,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: KGOC Global (Sales Training) || SSDN Technologies",
    timing: "3:06 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 197,
    date: "08-07-2026",
    name: "Amit",
    task: "Generative AI Training Requirement Support | SSDN Technologies",
    timing: "3:10 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 198,
    date: "08-07-2026",
    name: "Kamal",
    task: "Excellence Through Empowerment Program || Future Focus Infotech x SSDN Technologies ||",
    timing: "3:26 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 199,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: Vridhi Home Finance (Soft Skills - Leadership Development Training for Senior Managers Level 3) || SSDN Technologies",
    timing: "3:31 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 200,
    date: "08-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "3:37 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 201,
    date: "08-07-2026",
    name: "Kamal",
    task: "Introducing Excellence Through Empowerment Program || Wipro x SSDN Technologies ||",
    timing: "3:43 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 202,
    date: "08-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "4:04 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 203,
    date: "08-07-2026",
    name: "Kamal",
    task: "Re: Excellence Through Empowerment Program ||",
    timing: "4:10 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 204,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: Exploring Strategic Collaboration Opportunities with Mohindra Fasteners Limited || SSDN Technologies",
    timing: "4:27 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 205,
    date: "08-07-2026",
    name: "Amit",
    task: "Re: Data Analytics Training Requirement Support | SSDN Technologies",
    timing: "4:31 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 206,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: Viva Composite Panel (Posh Training) || SSDN Technologies",
    timing: "4:34 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 207,
    date: "08-07-2026",
    name: "Srishti",
    task: "Re: Kion Group (OT Cyber Security Training) || SSDN Technologies",
    timing: "4:38 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 208,
    date: "08-07-2026",
    name: "Kamal",
    task: "Introducing Excellence Through Empowerment Program ||",
    timing: "4:43 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
  {
    sno: 209,
    date: "08-07-2026",
    name: "Srishti",
    task: "Excellence Through Empowerment | A Year-Round Learning Solution",
    timing: "4:49 PM",
    remarks: "Pending (Awaiting Client)",
    completedTime: "",
    completedDate: "",
  },
];


  const fetchTasks = async () => {
    try {
      const response = await axios.get(
        "http://localhost:5000/api/tasks"
      );

      const backendTasks = Array.isArray(response.data)
        ? response.data
        : response.data.tasks || [];

      setTasks(backendTasks);

      setRecentTasks(
        [...backendTasks]
          .sort((a, b) =>
            String(b._id || "").localeCompare(
              String(a._id || "")
            )
          )
          .slice(0, 5)
      );
    } catch (error) {
      console.error("Error Fetching Tasks:", error);
      setTasks([]);
      setRecentTasks([]);
    }
  };

  // =========================
  // Load Tasks
  // =========================

  useEffect(() => {
    fetchTasks();
  }, []);
    // =========================
  // Profile Data
  // =========================

  const profileData = useMemo(() => {
    const employees = [...new Set(tasks.map(task => task.name))];

    return employees.map((employee) => {
      const employeeTasks = tasks.filter(
        task => task.name === employee
      );

      const completedTasks = employeeTasks.filter(
        task => task.remarks === "Closed"
      ).length;

      const pendingTasks =
        employeeTasks.length - completedTasks;

      const highPriority = employeeTasks.filter(
        task => task.priority === "High"
      ).length;

      const mediumPriority = employeeTasks.filter(
        task => task.priority === "Medium"
      ).length;

      const lowPriority = employeeTasks.filter(
        task => task.priority === "Low"
      ).length;

      const completionRate =
        employeeTasks.length === 0
          ? 0
          : Math.round(
              (completedTasks / employeeTasks.length) * 100
            );

      return {
        name: employee,
        totalTasks: employeeTasks.length,
        completedTasks,
        pendingTasks,
        highPriority,
        mediumPriority,
        lowPriority,
        completionRate,
        recentTasks: employeeTasks
          .slice(-5)
          .reverse(),
        tasks: employeeTasks,
      };
    });
  }, [tasks]);
    return (
    <Router>
      <div className="app-container">

        {/* Sidebar */}
        <Sidebar />

        {/* Main Content */}
        <main className="main-content">

          

            {/* Default Route */}
            <Routes>

  <Route
    path="/"
    element={<Navigate to="/dashboard" replace />}
  />

  <Route
    path="/dashboard"
    element={
      <Dashboard
        tasks={tasks}
        setTasks={setTasks}
        recentTasks={recentTasks}
        setRecentTasks={setRecentTasks}
        fetchTasks={fetchTasks}
      />
    }
  />

  <Route
    path="/operation"
    element={
      <Operation
        tasks={tasks}
        setTasks={setTasks}
        fetchTasks={fetchTasks}
      />
    }
  />

  <Route
    path="/analytics"
    element={
      <Analytics
        tasks={tasks}
      />
    }
  />

  <Route
    path="/team"
    element={
      <Team
        tasks={tasks}
        profileData={profileData}
      />
    }
  />

  <Route
    path="/profile"
    element={
      <Profile
        profileData={profileData}
      />
    }
  />

  <Route
    path="/profile/:name"
    element={
      <Profile
        profileData={profileData}
      />
    }
  />

  <Route
    path="*"
    element={<Navigate to="/dashboard" replace />}
  />

</Routes>

        </main>

      </div>
    </Router>
  );
}

export default App;